# Generated by Django 4.1.3 on 2022-11-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор портала'), ('developer', 'Разработчик')], default='developer', max_length=20),
        ),
    ]
