# Generated by Django 4.1.3 on 2022-11-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
